fix: dde-dock preview has notify
linuxdeepin/deepin-kwin pull request #108
Opened 2022-12-27 05:49 UTC by justforlxz

disable dde-dock preview notify

Log:

2022-12-27 05:58 UTC, zccrs requested changes

2022-12-27 05:58 UTC, zccrs commented on src/effects/screenshot/screenshotdbusinterface1.cpp
> +    qDebug() << "SKIP dde-dock preview";
qCDebug(KWIN_SCREENSHOT)

2022-12-29 02:07 UTC, wineee commented on src/effects/screenshot/screenshotdbusinterface1.cpp
> +        sendNotify = !file.readAll().compare("/usr/bin/dde-dock");
是否可以避免使用 /usr/bin/ 硬编码

2022-12-29 02:09 UTC, zccrs commented on src/effects/screenshot/screenshotdbusinterface1.cpp
> +        sendNotify = !file.readAll().compare("/usr/bin/dde-dock");
可以换成 QStandardPaths::findExecutable

2022-12-29 02:18 UTC, justforlxz commented on src/effects/screenshot/screenshotdbusinterface1.cpp
> +        sendNotify = !file.readAll().compare("/usr/bin/dde-dock");
我也不想硬编码的，但是毕竟这是一个截图接口，如果有一个二进制也改名 dde-dock，来用这个接口绕过截图通知就不好了。

2022-12-29 05:14 UTC, justforlxz commented
cc @wineee  添加上 -DDEFINE_DDE_DOCK_PATH=/usr/bin/ 这样的编译参数给 cmake 。

2022-12-29 05:17 UTC, wineee commented
我测试一下

2022-12-29 05:42 UTC, wineee approved these changes

2022-12-30 05:32 UTC, zccrs approved these changes

2022-12-30 05:33 UTC, merged

2023-02-13 08:15 UTC, wineee commented
等待此 pr 修复后再合入上游
https://github.com/NixOS/nixpkgs/pull/215075