chore: merge dde-kwin
linuxdeepin/deepin-kwin pull request #150
Opened 2023-03-15 13:20 UTC by justforlxz

stopped use dde-kwin project.

2023-03-15 14:35 UTC, wineee commented
安装路径尽量不要用硬编码

2023-03-16 03:31 UTC, justforlxz commented
> 安装路径尽量不要用硬编码

已修改

2023-03-16 03:46 UTC, wineee commented on deepin-wm-dbus/deepinwmfaker.cpp
> +    KConfig kglobalshortcutsrc("/etc/xdg/kglobalshortcutsrc");
能否使用 KSharedConfig::openConfig 避免硬编码
https://api.kde.org/frameworks/kconfig/html/classKSharedConfig.html

2023-03-16 05:25 UTC, BLumia commented on deepin-wm-dbus/deepinwmfaker.cpp
> +    KConfig kglobalshortcutsrc("/etc/xdg/kglobalshortcutsrc");
```suggestion
    KConfig kglobalshortcutsrc(KSharedConfig::openConfig(QStringLiteral("kglobalshortcutsrc"), KConfig::SimpleConfig));
```

可能是这样的（没实际尝试）。

以及如果要读的是我们安装的配置的话，是不是文件名也改一下更合适？

2023-03-16 08:38 UTC, zccrs requested changes

2023-03-16 08:38 UTC, zccrs commented on configures/CMakeLists.txt
> +        org.kde.kwin.splitmenu.display.json
应该是 org.deepin.kwin

2023-03-16 08:38 UTC, zccrs commented on configures/CMakeLists.txt
> +    install(
应该用 `install(SCRIPT`，不需要自己指定文件权限和安装路径

2023-03-16 08:38 UTC, zccrs commented on configures/kdeglobals
这个文件名怎么没改成 deepi- 开头呢

2023-03-16 08:38 UTC, zccrs commented on configures/kglobalshortcutsrc
同上

2023-03-16 08:38 UTC, zccrs commented on configures/klaunchrc
同上

2023-03-16 08:38 UTC, zccrs commented on configures/kwin_no_scale.in
> +    cp -n /etc/xdg/kglobalshortcutsrc $HOME/.config/kglobalshortcutsrc
前面的文件路径也应该通过变量传入，与 kglobalshortcutsrc 的安装时指定的路径一致

2023-03-16 08:38 UTC, zccrs commented on configures/kwin_no_scale.in
> +deepin-kwin_x11 :appFilePath=$EXECUTE_PATH/kwin_no_scale $@
尾部以一个空行结尾

2023-03-16 08:38 UTC, zccrs commented on configures/kwinrc
同文件名

2023-03-16 08:38 UTC, zccrs commented on configures/org.kde.kwin.splitmenu.display.json
> +  }
以空行结尾

2023-03-16 08:38 UTC, zccrs commented on deepin-wm-dbus/deepinwmfaker.cpp
添加copyright

2023-03-16 08:38 UTC, zccrs commented on deepin-wm-dbus/deepinwmfaker.h
copyright

2023-03-16 08:38 UTC, zccrs commented on deepin-wm-dbus/main.cpp
copyright

2023-03-16 08:39 UTC, zccrs commented
是不是少了东西呀，dde-kwin里只剩余 deepin-wm-dbus 了？

2023-03-16 08:42 UTC, justforlxz commented
> 是不是少了东西呀，dde-kwin里只剩余 deepin-wm-dbus 了？

交接之前就已经把插件合并到 deepin-kwin 里了，现在 dde-kwin 里只剩下配置文件和 wm-dbus。

2023-03-21 04:33 UTC, justforlxz commented on deepin-wm-dbus/deepinwmfaker.cpp
> +    KConfig kglobalshortcutsrc("/etc/xdg/kglobalshortcutsrc");
安装的配置文件都修改为 `deepin-` 前缀的了，同时也修改了所有代码中 load 的路径/文件名。

2023-03-21 04:35 UTC, wineee commented on configures/CMakeLists.txt
> +        "/etc/xdg"
```suggestion
        "${CMAKE_INSTALL_SYSCONFDIR}/xdg"
```

2023-03-21 05:30 UTC, Zeno-sole approved these changes

2023-03-21 05:32 UTC, zccrs approved these changes

2023-03-21 05:34 UTC, merged