Optimize/scissor
linuxdeepin/deepin-kwin pull request #160
Opened 2023-04-04 13:18 UTC by justforlxz

2023-04-04 13:33 UTC, justforlxz commented
追加一个不绘制阴影的。

![telegram-cloud-photo-size-5-6152251007971734659-y](https://user-images.githubusercontent.com/12298476/229809396-139ad7b2-1d94-4450-a799-84d0ab969920.jpg)

2023-04-04 14:57 UTC, BLumia requested changes

2023-04-04 14:57 UTC, BLumia commented on src/effects/scissorwindow/scissorwindow.h
> +    // void drawWindow(EffectWindow* w, int mask, const QRegion &region, WindowPaintData& data) override;
```suggestion
```

2023-04-06 04:24 UTC, BLumia submitted a review, later dismissed

2023-04-06 08:06 UTC, BLumia approved these changes

2023-04-07 01:29 UTC, zccrs approved these changes

2023-04-07 01:30 UTC, merged