chore: all windows use 18 rounded corners by default
linuxdeepin/deepin-kwin pull request #171
Opened 2023-04-28 02:41 UTC by justforlxz

- remove useless cache map
- set 18 to default corner

Closed: https://github.com/linuxdeepin/developer-center/issues/4241

2023-05-05 06:32 UTC, zccrs commented on src/effects/blur/blur.cpp
> -                const QVariant valueRadius = w->data(WindowRadiusRole);
还不如原本这样写，避免多次调用 data 函数

2023-05-05 06:32 UTC, zccrs commented on src/effects/scissorwindow/scissorwindow.cpp
> -    for (int i = 0; i < NCorners; ++i) {
为什么删了

2023-05-05 06:32 UTC, zccrs commented on src/effects/scissorwindow/scissorwindow.cpp
> +    painter.setBrush(QColor(255,255,255,255));
为什么需要改变颜色？

2023-05-05 06:35 UTC, zccrs requested changes

2023-05-05 06:35 UTC, zccrs commented on src/plugins/kdecorations/deepin-chameleon/chameleonshadow.cpp
> +QString ChameleonShadow::buildShadowCacheKey(KWin::EffectWindow *effect, const ChameleonTheme::ThemeConfig &config, qreal scale)
在这个接口上依赖 KWin::EffectWindow 对象不是个好的设计，可以增加一个 const QPointF maxWindowRadius 这样的参数。

2023-05-05 07:55 UTC, justforlxz commented on src/effects/scissorwindow/scissorwindow.cpp
> +    painter.setBrush(QColor(255,255,255,255));
删除的是没有使用的，这里是把 drawWindow 里工作的代码移动过来了。

2023-05-06 03:25 UTC, zccrs approved these changes

2023-05-06 03:27 UTC, zccrs requested changes

2023-05-06 03:27 UTC, zccrs commented on src/effects/scissorwindow/scissorwindow.cpp
> -        || (mask & (PAINT_SCREEN_WITH_TRANSFORMED_WINDOWS)))
不是在 https://github.com/linuxdeepin/deepin-kwin/pull/175 中修改了吗

2023-05-06 08:28 UTC, zccrs requested changes

2023-05-06 08:28 UTC, zccrs commented on src/effects/blur/blur.cpp
> +                    double cornerRadius = w->data(WindowRadiusRole).toPointF().x();
为什么只用 x 方向的值呢，如果这个圆角效果不支持分别控制x和y的圆角半径，可以是取x、y的最大值，或者是最小值。而不应该只取其中一个。

2023-05-06 08:28 UTC, zccrs commented on src/plugins/kdecorations/deepin-chameleon/chameleonshadow.cpp
> +        window_radius = maxWindowRadius;
为什么直接就等于最大的raduis了？

2023-05-08 01:52 UTC, zccrs requested changes

2023-05-08 01:52 UTC, zccrs commented on src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
> +            maxWindowRadius = QPointF(effect->width() / 2.0, effect->height() / 2.0);
为什么在这个if里边赋值呢，如果没有进这个if，后续又调用了 ChameleonShadow::instance()->getShadow 会怎么样？

2023-05-08 02:03 UTC, justforlxz commented on src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
> +            maxWindowRadius = QPointF(effect->width() / 2.0, effect->height() / 2.0);
没有的话就说明没设置圆角大小，在 getShadow 里有判断存不存在 theme_config.radius.

2023-05-08 02:08 UTC, zccrs approved these changes

2023-05-08 02:09 UTC, merged