fix: incorrect window radius of 3rdparty window
linuxdeepin/deepin-kwin pull request #211
Opened 2023-08-28 07:38 UTC by asterwyx

Due to start order, kwin cannot get xsettings set by startdde from root window. Just use dbus to fetch global window radius info.

Log: fix incorrect window radius of 3rdparty window

2023-08-29 03:16 UTC, justforlxz requested changes

2023-08-29 03:16 UTC, justforlxz commented on src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
> +        auto val = reply.value().toInt();
在这里调用 `ChameleonConfig::onAppearanceChanged`，不要写两份

2023-08-29 03:26 UTC, zccrs requested changes

2023-08-29 03:26 UTC, zccrs commented on src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
> +        auto val = reply.value().toInt();
应该是把下面这段提取和独立到一个函数里，在 onAppearanceChanged 中和这里都调用提取出来的函数
````
if (radius != m_globalWindowRadius) {
            m_globalWindowRadius = radius;
            Q_EMIT globalWindowRadiusChanged(m_globalWindowRadius);
        }
````

2023-08-29 03:26 UTC, zccrs commented on src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
> +        QDBusPendingCallWatcher *radiusWatcher = new QDBusPendingCallWatcher(radius, this);
在哪销毁的？需要自己销毁吗？

2023-08-29 06:17 UTC, asterwyx commented on src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
> +        QDBusPendingCallWatcher *radiusWatcher = new QDBusPendingCallWatcher(radius, this);
在槽函数里面销毁了

2023-09-01 05:17 UTC, justforlxz approved these changes

2023-09-01 07:23 UTC, justforlxz commented
/merge

2023-09-01 07:56 UTC, merged