fix: validProperties not update(#6579)
linuxdeepin/deepin-kwin pull request #230
Opened 2024-01-12 06:56 UTC by kegechen

Issue: https://github.com/linuxdeepin/developer-center/issues/6579

2024-01-12 06:58 UTC, kegechen commented
https://github.com/linuxdeepin/qt5platform-plugins/pull/227

2024-01-15 09:08 UTC, justforlxz approved these changes

2024-01-15 09:10 UTC, zccrs requested changes
这样很不好理解，从DTK里解决

2024-01-15 09:26 UTC, zccrs approved these changes

2024-01-15 09:27 UTC, kegechen commented
/merge

2024-01-15 09:27 UTC, kegechen commented
TODO： xcb 版本依赖要改一下

2024-01-15 09:27 UTC, merged