fix: titlebar color not change
linuxdeepin/deepin-kwin pull request #234
Opened 2024-01-24 03:51 UTC by Decodetalkers

listen to fakewm signal

Log:

2024-01-24 05:10 UTC, kegechen requested changes

2024-01-24 05:10 UTC, kegechen commented on src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
> +                                          QStringLiteral("com.deepin.wm"),
```suggestion
    QDBusConnection::sessionBus().connect(DBUS_DEEPIN_WM_SERVICE,
                                                       DBUS_DEEPIN_WM_OBJ,
                                                       DBUS_DEEPIN_WM_INTF),
```

2024-01-24 05:10 UTC, kegechen commented on src/plugins/kdecorations/deepin-chameleon/chameleonconfig.cpp
> -
?

2024-01-24 05:18 UTC, kegechen approved these changes

2024-01-24 05:22 UTC, kegechen commented
https://github.com/linuxdeepin/developer-center/issues/5685

2024-01-24 06:53 UTC, justforlxz approved these changes

2024-01-24 08:34 UTC, Decodetalkers commented
/check obs

2024-01-24 08:45 UTC, Decodetalkers commented
/check obs

2024-01-24 09:39 UTC, Decodetalkers commented
/check obs

2024-01-25 01:40 UTC, Decodetalkers commented
/merge

2024-01-25 01:40 UTC, merged